### ISSUE TITLE
Doesn't stop voting at max karma

### ISSUE THREAD

**Issue by c0rnfl4k3s** [otaviotech/photofeeler-bot#2]
The bot should be able to detect when karma is full and stop voting. 
Otherwise it's a great bot!

**Comment by otaviotech** [comment]
Thanks for your suggestion, @c0rnfl4k3s!
I think it would be a great improvement to the bot.
Feel free to send a pull request, i'd love to have this feature in the bot.

**Comment by c0rnfl4k3s** [comment]
Done! :)
